name: Daily Remote Job Search

on:
  schedule:
    # 18:00 UTC = 00:00 Bangladesh time
    - cron: "0 18 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  search-jobs:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Search jobs
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python job_search.py

      - name: Save seen jobs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add seen_jobs.json

          git diff --cached --quiet || git commit -m "Update seen jobs"

          git push
